### PR TITLE
Extract and parse datePublished and dateModified fields

### PR DESCRIPTION
**Pull request by ashishb**

### CODE REVIEW

**Review by sananguliyev — APPROVED** [review]
LGTM

**Review by fmartingr — CHANGES_REQUESTED** [review]
Thanks for the contribution @ashishb ! Could you add the appropriate content for testing this? Considering you loop over several formats it would be nice to know that fields are parsed and extracted correctly, maybe adding the expected dates in several of the articles in the `test-files` dir.

**Comment by ABSanthosh** [comment]
This PR should be closed I believe. This has been addressed in #41, based on the issue #20.

**Comment by fmartingr** [comment]
Thank you for the ping!

Closed by #41

**Pull request closed without merging**
